### ISSUE TITLE
Problem with AssppPro

### ISSUE THREAD

**Issue by tageniu** [TrollStoreTV/Release#1]
Hi, thank you for your work. When I use your trollstore version w/ AssppPro here ([https://t.me/iOS_TrollStore/3185](https://t.me/iOS_TrollStore/3185)), the ipa failed to install w/ the following error:

> 2024-08-05 23:47:51.512 trollstorehelper[11801:2359015] trollstorehelper invoked with arguments: (
>     install,
>     custom,
>     skipSign,
>     "/private/var/mobile/Containers/Data/Application/FD675465-2034-450A-834E-DE68CAE44F54/Documents/Inbox/The Weather Channel_295646461_867749396_14.9.1.ipa"
> )
> 2024-08-05 23:47:57.135 trollstorehelper[11801:2359015] #####error,The item being installed did not contain an app with bundle ID "", but it did contain app(s) with bundle ID(s): {(
>     "com.weather.TWC"
> )}
> 2024-08-05 23:47:57.135 trollstorehelper[11801:2359015] trollstorehelper returning 255

I wonder what's the reason and if you can fix the issue on your side. Thank you in advance.

**Comment by TrollStoreTV** [comment]
Fix it. please update.
